version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/app
    external_links:
      - mysqldb
    links:
      - redisdb
    restart: always
    ports:
      - "8081:80"
    environment:
      - "REDISTOGO_URL=redis://redisdb:6379"
      - "VIRTUAL_HOST=stalker.zense.co.in"
    cpu_shares: 30
    mem_limit: 512m
    networks:
      - production
      - default

  worker:
    build: .
    volumes:
      - ./:/app
    external_links:
      - mysqldb
    links:
      - redisdb
    restart: always
    environment:
      - "REDISTOGO_URL=redis://redisdb:6379"
    command: python worker.py
    cpu_shares: 30
    mem_limit: 512m
    networks:
      - production
      - default

  redisdb:
    image: redis
    networks:
      - default

networks:
  production:
    external: true


# We are using an external link for mysql because we already have a mysql running for us in producton env
# For local development environmnt you have to run a mysql container separately to make this work
# Example:
# docker run --name mysqldb -e MYSQL_ROOT_PASSWORD=thanks123 -d mysql
# docker-compose up
